In [62]:
import numpy as np
import matplotlib.pyplot as plt

# Sifirdan K-NN

`numpy` ve temel python fonksiyonalitesini kullanarak sifirdan k-NN regresyon algoritmasini yaziniz.

# 0. Isinma

## 0.a. Minkowski mesafeleri

Verilen iki vektor ve `p` parametresi icin Minkowski mesafesini hesaplayacak fonksiyonu yaziniz.

In [38]:
def minkowskiMesafesi(x1, x2, p=2):
    """
    Minkowski mesafesi, Oklit mesafesinin genellenmis halidir.
    p = 1 ise Manhattan mesafesi, p = 2 ise Euclidean mesafesi, p = inf ise Chebyshev mesafesi gibi ozel durumlari mevcuttur.
    """
    return None

### 0.a.I. Test

Mesafe hesaplayicinizi asagidaki durumlar icin test ediniz:

##### Test 1

In [40]:
v1, v2 = np.array([1, 2, 3]), np.array([1, 2, 3])
print(minkowskiMesafesi(v1, v2))

0.0


##### Test 2

In [41]:
v1, v2 = np.ones(64), np.ones(64) * 2.
print(minkowskiMesafesi(v1, v2))

8.0


##### Test 3

In [42]:
v1, v2 = np.ones(64), np.ones(64) * 2.
print(minkowskiMesafesi(v1, v2, p=1))

64.0


##### Test 4

In [45]:
v1, v2 = np.array([1,1,1]), np.array([2,2,8])
print(minkowskiMesafesi(v1, v2, p=np.inf))

7.0


# 1. Sifirdan K-NN

## 1.a. Broadcasting

Asagida verilen (m, n) ve (q, n) boyutlu iki matris, n-boyutlu uzayda sirasiyla m ve q sayida noktalari temsil etmektedir.

In [30]:
m, q, n = 9, 3, 2
np.random.seed(0)
M1 = np.random.randn(m, n)
M2 = np.random.randn(q, n)
print("M1 matrisi: \n", M1)
print("M2 matrisi: \n", M2)

M1 matrisi: 
 [[ 1.76405235  0.40015721]
 [ 0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721]
 [-0.10321885  0.4105985 ]
 [ 0.14404357  1.45427351]
 [ 0.76103773  0.12167502]
 [ 0.44386323  0.33367433]
 [ 1.49407907 -0.20515826]]
M2 matrisi: 
 [[ 0.3130677  -0.85409574]
 [-2.55298982  0.6536186 ]
 [ 0.8644362  -0.74216502]]


Her bir noktanin birbirlerine olan mesafesini gosterecek bir matris oluşturulmak istenmektedir.

### 1.a.I.

Elde edilecek mesafe matrisinin boyutu ne olacaktir?

### 1.a.II.

Mesafe matrisini elde etmek icin gerekli islemleri yapiniz. (`minkowskiMesafe` fonksiyonunu ilk tercih olarak kullanmamaya calisiniz.)

> `for` dongusu kullanmadan, broadcast ile bu problemi nasil cozebilirdiniz?

## 1.b. Argsort

`M2` matrisindeki `1` indeks numarali noktaya `M1` matrisinden en yakin 3 noktanin indeks numaralari nedir? 

Cevabi verecek islemi `numpy` ile yapiniz.

## 1.c. KNN

Yukarida verilen parcalari birlestirerek bir *K-NN* regressor elde edecegiz.

### 1.c.I.

Asagida iskeleti verilmis `class`'i kullanarak regressorunuzu hazirlayiniz.

In [ ]:
class KNNRegressor:
    def __init__(self, *args):
        # Kullanicidan komsu sayisi `k` parametresini alarak uygun sekilde kaydedin.
        # `*args` ifadesini uyugn sekilde degistirin.
        return
    
    def fit(self, *args):
        # Kullanicidan X ve y verilerini alarak uygun sekilde kaydedin
        # `*args`` ifadesini uygun sekilde degistirin.


        return self # return ifadesini degistirmeye ihtiyac yoktur.

    def predict(self, *args):
        # Kullanicidan sorgu noktalarini alacak sekilde `*args` ifadesini degistirin.

        # Her sorgu noktasina egitim verisindeki en yakin `k` ornegin indekslerini bulun.
        # Indeksleri kullanarak egitim cevaplarindaki en yakin `k` ornegin etiketlerini getirin.
        # Her sorgu icin en yakin `k` ornegin y ortalamalarini dondurun.
        return None

### 1.c.II.

Regressorunuzu asagidaki durumlar icin `sklearn.neighbors.KNeighborsRegressor` classinin cevaplarina karsi test ediniz:

In [33]:
from sklearn import neighbors

##### Test 1

In [31]:
X_train, X_test, y_train = M1, M2, np.random.randn(m)

In [32]:
KNNRegressor(k=5).fit(X_train, y_train).predict(X_test)

array([ 0.19818391,  0.66961282, -0.09922023])

In [34]:
neighbors.KNeighborsRegressor(n_neighbors=5).fit(X_train, y_train).predict(X_test)

array([ 0.19818391,  0.66961282, -0.09922023])

##### Test 2

In [35]:
m, n, q = 900, 12, 8
X_train, X_test, y_train = np.random.randn(m, n), np.random.randn(q, n), np.random.randn(m)

In [36]:
KNNRegressor(k=5).fit(X_train, y_train).predict(X_test)

array([ 0.7517607 , -0.14492408,  0.14405955,  0.0984835 ,  0.46297028,
       -0.19082287,  0.08268905, -0.49187292])

In [37]:
neighbors.KNeighborsRegressor(n_neighbors=5).fit(X_train, y_train).predict(X_test)

array([ 0.7517607 , -0.14492408,  0.14405955,  0.0984835 ,  0.46297028,
       -0.19082287,  0.08268905, -0.49187292])